export const beneficiariesData = [
  {
    beneficiaryName: "अजय",
    beneficiaryId: "abc123xyz789",
    khatauniSankhya: "1",
    faldaarBhumiPrice: 100000,
    gairFaldaarBhumiPrice: 5000,
    housePrice: 500000,
    serialNumber: "1",
    khasraNumber: "12/3",
    acquiredKhasraNumber: "12/3/4",
    areaVariety: "13",
    acquiredRakbha: "134",
    beneficiaryShare: "34",
    acquiredBeneficiaryShare: "00-01-23",
    landPricePerSqMt: "5000",
    villageName: "One",
    verificationDetails: {
      level: "0",
      status: "1",
      updatedBy: "Nitin",
      updatedAt: "10 OCT 2024",
      userRole: "1",
      userName: "Nitin",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "एक",
    aadhar: "301",
    pancard: "301",
    totalCompensation: "75.40",
    paymentStatus: "2",
    paymentDate: "10/08/2024",
    verificationStatus: "",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "66eee1c0f82f325408a96bf8",
        updatedAt: "12/10/2024",
        message: "Hello, Please check the attached doc.",
        userRole: "3",
        name: "Nitin",
        attachment:
          "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes, I have checked",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "66eee1c0f82f325408a96bf8",
        updatedAt: "12/10/2024",
        message: "Any update about this?",
        userRole: "3",
        name: "Nitin",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all. Please take a look at this doc also.",
        userRole: "3",
        name: "User 3",
        attachment:
          "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Ok I will.",
        userRole: "1",
        name: "User 2",
        type: "img",
        attachment:
          "https://media.istockphoto.com/id/462568451/photo/internet-crime-and-electronic-banking-security.jpg?b=1&s=612x612&w=0&k=20&c=_3rQ8QlvaOxFecftSWuOG_hntpJFEGWfSx99vWu-P-U=",
      },
    ],
  },
  {
    beneficiaryName: "अजय2",
    beneficiaryId: "abc123xyz7129",
    khatauniSankhya: "1",
    serialNumber: "3",
    khasraNumber: "12/3",
    acquiredKhasraNumber: "12/3/4",
    areaVariety: "13",
    acquiredRakbha: "134",
    beneficiaryShare: "34",
    acquiredBeneficiaryShare: "00-01-23",
    landPricePerSqMt: "5000",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "Nitin",
      updatedAt: "10 OCT 2024",
      userRole: "1",
      userName: "Nitin",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "एक",
    aadhar: "350",
    pancard: "350",
    totalCompensation: "75.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "विकास",
    beneficiaryId: "def456uvw234",
    khatauniSankhya: "1",
    serialNumber: "2",
    khasraNumber: "13/4",
    acquiredKhasraNumber: "13/4/5",
    areaVariety: "15",
    acquiredRakbha: "140",
    beneficiaryShare: "35",
    acquiredBeneficiaryShare: "00-01-24",
    landPricePerSqMt: "5100",
    villageName: "One",
    verificationDetails: {
      level: "0",
      status: "1",
      updatedBy: "Nitin",
      updatedAt: "10 OCT 2024",
      userRole: "1",
      userName: "Nitin",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "एक",
    aadhar: "302",
    pancard: "302",
    totalCompensation: "85.20",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
        attachment:
          "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
        attachment:
          "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "सुमित",
    beneficiaryId: "ghi789rst456",
    khatauniSankhya: "2",
    serialNumber: "3",
    khasraNumber: "14/5",
    acquiredKhasraNumber: "14/5/6",
    areaVariety: "14",
    acquiredRakbha: "145",
    beneficiaryShare: "36",
    acquiredBeneficiaryShare: "00-01-25",
    landPricePerSqMt: "5200",
    villageName: "Two",
    verificationDetails: {
      level: "0",
      status: "",
      updatedBy: "",
      updatedAt: "",
      userRole: "",
      userName: "",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "दो",
    aadhar: "303",
    pancard: "303",
    totalCompensation: "90.10",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "मोहित",
    beneficiaryId: "jkl012opq789",
    khatauniSankhya: "2",
    serialNumber: "4",
    khasraNumber: "15/6",
    acquiredKhasraNumber: "15/6/7",
    areaVariety: "16",
    acquiredRakbha: "150",
    beneficiaryShare: "37",
    acquiredBeneficiaryShare: "00-01-26",
    landPricePerSqMt: "5300",
    villageName: "Two",
    verificationDetails: {
      level: "0",
      status: "",
      updatedBy: "",
      updatedAt: "",
      userRole: "",
      userName: "",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "दो",
    aadhar: "304",
    pancard: "304",
    totalCompensation: "92.60",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "नीलम",
    beneficiaryId: "mno345rst678",
    khatauniSankhya: "3",
    serialNumber: "5",
    khasraNumber: "16/7",
    acquiredKhasraNumber: "16/7/8",
    areaVariety: "17",
    acquiredRakbha: "155",
    beneficiaryShare: "38",
    acquiredBeneficiaryShare: "00-01-27",
    landPricePerSqMt: "5400",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तीन",
    aadhar: "305",
    pancard: "305",
    totalCompensation: "75.50",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "राजेश",
    beneficiaryId: "pqr678uvw901",
    khatauniSankhya: "3",
    serialNumber: "6",
    khasraNumber: "17/8",
    acquiredKhasraNumber: "17/8/9",
    areaVariety: "18",
    acquiredRakbha: "160",
    beneficiaryShare: "39",
    acquiredBeneficiaryShare: "00-01-28",
    landPricePerSqMt: "5500",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तीन",
    aadhar: "306",
    pancard: "306",
    totalCompensation: "85.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "रितु",
    beneficiaryId: "stu901xyz234",
    khatauniSankhya: "4",
    serialNumber: "7",
    khasraNumber: "18/9",
    acquiredKhasraNumber: "18/9/10",
    areaVariety: "19",
    acquiredRakbha: "165",
    beneficiaryShare: "40",
    acquiredBeneficiaryShare: "00-01-29",
    landPricePerSqMt: "5600",
    villageName: "Four",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चार",
    aadhar: "307",
    pancard: "307",
    totalCompensation: "95.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "दीप्ति",
    beneficiaryId: "vwx234abc567",
    khatauniSankhya: "4",
    serialNumber: "8",
    khasraNumber: "19/10",
    acquiredKhasraNumber: "19/10/11",
    areaVariety: "20",
    acquiredRakbha: "170",
    beneficiaryShare: "41",
    acquiredBeneficiaryShare: "00-01-30",
    landPricePerSqMt: "5700",
    villageName: "Four",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चार",
    aadhar: "308",
    pancard: "308",
    totalCompensation: "98.20",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सुनील",
    beneficiaryId: "yzx345def678",
    khatauniSankhya: "5",
    serialNumber: "9",
    khasraNumber: "20/11",
    acquiredKhasraNumber: "20/11/12",
    areaVariety: "21",
    acquiredRakbha: "175",
    beneficiaryShare: "42",
    acquiredBeneficiaryShare: "00-01-31",
    landPricePerSqMt: "5800",
    villageName: "Five",
    villageId: "09yh4567898uyg",
    villageNameHindi: "पाँच",
    aadhar: "309",
    pancard: "309",
    totalCompensation: "101.30",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सुमन",
    beneficiaryId: "abc678opq901",
    khatauniSankhya: "5",
    serialNumber: "10",
    khasraNumber: "21/12",
    acquiredKhasraNumber: "21/12/13",
    areaVariety: "22",
    acquiredRakbha: "180",
    beneficiaryShare: "43",
    acquiredBeneficiaryShare: "00-01-32",
    landPricePerSqMt: "5900",
    villageName: "Five",
    villageId: "09yh4567898uyg",
    villageNameHindi: "पाँच",
    aadhar: "310",
    pancard: "310",
    totalCompensation: "104.50",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अरविंद",
    beneficiaryId: "def789ijk234",
    khatauniSankhya: "6",
    serialNumber: "11",
    khasraNumber: "22/13",
    acquiredKhasraNumber: "22/13/14",
    areaVariety: "23",
    acquiredRakbha: "185",
    beneficiaryShare: "44",
    acquiredBeneficiaryShare: "00-01-33",
    landPricePerSqMt: "6000",
    villageName: "Six",
    villageId: "09yh4567898uyg",
    villageNameHindi: "छह",
    aadhar: "311",
    pancard: "311",
    totalCompensation: "107.60",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "प्रीति",
    beneficiaryId: "ghi890lmn345",
    khatauniSankhya: "6",
    serialNumber: "12",
    khasraNumber: "23/14",
    acquiredKhasraNumber: "23/14/15",
    areaVariety: "24",
    acquiredRakbha: "190",
    beneficiaryShare: "45",
    acquiredBeneficiaryShare: "00-01-34",
    landPricePerSqMt: "6100",
    villageName: "Six",
    villageId: "09yh4567898uyg",
    villageNameHindi: "छह",
    aadhar: "312",
    pancard: "312",
    totalCompensation: "110.70",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सौरभ",
    beneficiaryId: "jkl901mno678",
    khatauniSankhya: "7",
    serialNumber: "13",
    khasraNumber: "24/15",
    acquiredKhasraNumber: "24/15/16",
    areaVariety: "25",
    acquiredRakbha: "195",
    beneficiaryShare: "46",
    acquiredBeneficiaryShare: "00-01-35",
    landPricePerSqMt: "6200",
    villageName: "Seven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सात",
    aadhar: "313",
    pancard: "313",
    totalCompensation: "113.80",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अमित",
    beneficiaryId: "mno123pqr456",
    khatauniSankhya: "7",
    serialNumber: "14",
    khasraNumber: "25/16",
    acquiredKhasraNumber: "25/16/17",
    areaVariety: "26",
    acquiredRakbha: "200",
    beneficiaryShare: "47",
    acquiredBeneficiaryShare: "00-01-36",
    landPricePerSqMt: "6300",
    villageName: "Seven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सात",
    aadhar: "314",
    pancard: "314",
    totalCompensation: "116.90",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "मनोज",
    beneficiaryId: "pqr234stu567",
    khatauniSankhya: "8",
    serialNumber: "15",
    khasraNumber: "26/17",
    acquiredKhasraNumber: "26/17/18",
    areaVariety: "27",
    acquiredRakbha: "205",
    beneficiaryShare: "48",
    acquiredBeneficiaryShare: "00-01-37",
    landPricePerSqMt: "6400",
    villageName: "Eight",
    villageId: "09yh4567898uyg",
    villageNameHindi: "आठ",
    aadhar: "315",
    pancard: "315",
    totalCompensation: "120.00",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "कुणाल",
    beneficiaryId: "stu345vwx678",
    khatauniSankhya: "8",
    serialNumber: "16",
    khasraNumber: "27/18",
    acquiredKhasraNumber: "27/18/19",
    areaVariety: "28",
    acquiredRakbha: "210",
    beneficiaryShare: "49",
    acquiredBeneficiaryShare: "00-01-38",
    landPricePerSqMt: "6500",
    villageName: "Eight",
    villageId: "09yh4567898uyg",
    villageNameHindi: "आठ",
    aadhar: "316",
    pancard: "316",
    totalCompensation: "123.10",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "नरेश",
    beneficiaryId: "vwx456yzx789",
    khatauniSankhya: "9",
    serialNumber: "17",
    khasraNumber: "28/19",
    acquiredKhasraNumber: "28/19/20",
    areaVariety: "29",
    acquiredRakbha: "215",
    beneficiaryShare: "50",
    acquiredBeneficiaryShare: "00-01-39",
    landPricePerSqMt: "6600",
    villageName: "Nine",
    villageId: "09yh4567898uyg",
    villageNameHindi: "नौ",
    aadhar: "317",
    pancard: "317",
    totalCompensation: "126.20",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सचिन",
    beneficiaryId: "yzx567abc890",
    khatauniSankhya: "9",
    serialNumber: "18",
    khasraNumber: "29/20",
    acquiredKhasraNumber: "29/20/21",
    areaVariety: "30",
    acquiredRakbha: "220",
    beneficiaryShare: "51",
    acquiredBeneficiaryShare: "00-01-40",
    landPricePerSqMt: "6700",
    villageName: "Nine",
    villageId: "09yh4567898uyg",
    villageNameHindi: "नौ",
    aadhar: "318",
    pancard: "318",
    totalCompensation: "129.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "रश्मि",
    beneficiaryId: "abc678def901",
    khatauniSankhya: "10",
    serialNumber: "19",
    khasraNumber: "30/21",
    acquiredKhasraNumber: "30/21/22",
    areaVariety: "31",
    acquiredRakbha: "225",
    beneficiaryShare: "52",
    acquiredBeneficiaryShare: "00-01-41",
    landPricePerSqMt: "6800",
    villageName: "Ten",
    villageId: "09yh4567898uyg",
    villageNameHindi: "दस",
    aadhar: "319",
    pancard: "319",
    totalCompensation: "132.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "शिव",
    beneficiaryId: "def789ghi234",
    khatauniSankhya: "10",
    serialNumber: "20",
    khasraNumber: "31/22",
    acquiredKhasraNumber: "31/22/23",
    areaVariety: "32",
    acquiredRakbha: "230",
    beneficiaryShare: "53",
    acquiredBeneficiaryShare: "00-01-42",
    landPricePerSqMt: "6900",
    villageName: "Ten",
    villageId: "09yh4567898uyg",
    villageNameHindi: "दस",
    aadhar: "320",
    pancard: "320",
    totalCompensation: "135.50",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "प्रियंका",
    beneficiaryId: "ghi890jkl345",
    khatauniSankhya: "11",
    serialNumber: "21",
    khasraNumber: "32/23",
    acquiredKhasraNumber: "32/23/24",
    areaVariety: "33",
    acquiredRakbha: "235",
    beneficiaryShare: "54",
    acquiredBeneficiaryShare: "00-01-43",
    landPricePerSqMt: "7000",
    villageName: "Eleven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "ग्यारह",
    aadhar: "321",
    pancard: "321",
    totalCompensation: "138.60",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सुप्रिया",
    beneficiaryId: "jkl901mno456",
    khatauniSankhya: "11",
    serialNumber: "22",
    khasraNumber: "33/24",
    acquiredKhasraNumber: "33/24/25",
    areaVariety: "34",
    acquiredRakbha: "240",
    beneficiaryShare: "55",
    acquiredBeneficiaryShare: "00-01-44",
    landPricePerSqMt: "7100",
    villageName: "Eleven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "ग्यारह",
    aadhar: "322",
    pancard: "322",
    totalCompensation: "141.70",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "पल्लवी",
    beneficiaryId: "mno012pqr567",
    khatauniSankhya: "12",
    serialNumber: "23",
    khasraNumber: "34/25",
    acquiredKhasraNumber: "34/25/26",
    areaVariety: "35",
    acquiredRakbha: "245",
    beneficiaryShare: "56",
    acquiredBeneficiaryShare: "00-01-45",
    landPricePerSqMt: "7200",
    villageName: "",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बारह",
    aadhar: "323",
    pancard: "323",
    totalCompensation: "144.80",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सोनू",
    beneficiaryId: "pqr123stu678",
    khatauniSankhya: "12",
    serialNumber: "24",
    khasraNumber: "35/26",
    acquiredKhasraNumber: "35/26/27",
    areaVariety: "36",
    acquiredRakbha: "250",
    beneficiaryShare: "57",
    acquiredBeneficiaryShare: "00-01-46",
    landPricePerSqMt: "7300",
    villageName: "",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बारह",
    aadhar: "324",
    pancard: "324",
    totalCompensation: "147.90",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अनिल",
    beneficiaryId: "stu234vwx789",
    khatauniSankhya: "13",
    serialNumber: "25",
    khasraNumber: "36/27",
    acquiredKhasraNumber: "36/27/28",
    areaVariety: "37",
    acquiredRakbha: "255",
    beneficiaryShare: "58",
    acquiredBeneficiaryShare: "00-01-47",
    landPricePerSqMt: "7400",
    villageName: "Thirteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तेरह",
    aadhar: "325",
    pancard: "325",
    totalCompensation: "151.00",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "शिल्पा",
    beneficiaryId: "vwx345yzx890",
    khatauniSankhya: "13",
    serialNumber: "26",
    khasraNumber: "37/28",
    acquiredKhasraNumber: "37/28/29",
    areaVariety: "38",
    acquiredRakbha: "260",
    beneficiaryShare: "59",
    acquiredBeneficiaryShare: "00-01-48",
    landPricePerSqMt: "7500",
    villageName: "Thirteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तेरह",
    aadhar: "326",
    pancard: "326",
    totalCompensation: "154.10",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "राहुल",
    beneficiaryId: "yzx456abc012",
    khatauniSankhya: "14",
    serialNumber: "27",
    khasraNumber: "38/29",
    acquiredKhasraNumber: "38/29/30",
    areaVariety: "39",
    acquiredRakbha: "265",
    beneficiaryShare: "60",
    acquiredBeneficiaryShare: "00-01-49",
    landPricePerSqMt: "7600",
    villageName: "Fourteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चौदह",
    aadhar: "327",
    pancard: "327",
    totalCompensation: "157.20",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "जया",
    beneficiaryId: "abc567def123",
    khatauniSankhya: "14",
    serialNumber: "28",
    khasraNumber: "39/30",
    acquiredKhasraNumber: "39/30/31",
    areaVariety: "40",
    acquiredRakbha: "270",
    beneficiaryShare: "61",
    acquiredBeneficiaryShare: "00-01-50",
    landPricePerSqMt: "7700",
    villageName: "Fourteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चौदह",
    aadhar: "328",
    pancard: "328",
    totalCompensation: "160.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "हेमंत",
    beneficiaryId: "def678ghi234",
    khatauniSankhya: "15",
    serialNumber: "29",
    khasraNumber: "40/31",
    acquiredKhasraNumber: "40/31/32",
    areaVariety: "41",
    acquiredRakbha: "275",
    beneficiaryShare: "62",
    acquiredBeneficiaryShare: "00-01-51",
    landPricePerSqMt: "7800",
    villageName: "Fifteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "पंद्रह",
    aadhar: "329",
    pancard: "329",
    totalCompensation: "163.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "रिंकू",
    beneficiaryId: "ghi789jkl345",
    khatauniSankhya: "15",
    serialNumber: "30",
    khasraNumber: "41/32",
    acquiredKhasraNumber: "41/32/33",
    areaVariety: "42",
    acquiredRakbha: "280",
    beneficiaryShare: "63",
    acquiredBeneficiaryShare: "00-01-52",
    landPricePerSqMt: "7900",
    villageName: "Fifteen",
    villageId: "09yh4567898uyg",
    villageNameHindi: "पंद्रह",
    aadhar: "330",
    pancard: "330",
    totalCompensation: "166.50",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "प्रणव",
    beneficiaryId: "jkl890mno456",
    khatauniSankhya: "16",
    serialNumber: "31",
    khasraNumber: "42/33",
    acquiredKhasraNumber: "42/33/34",
    areaVariety: "43",
    acquiredRakbha: "285",
    beneficiaryShare: "64",
    acquiredBeneficiaryShare: "00-01-53",
    landPricePerSqMt: "8000",
    villageName: "Two",
    verificationDetails: {
      level: "0",
      status: "",
      updatedBy: "",
      updatedAt: "",
      userRole: "",
      userName: "",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "सोलह",
    aadhar: "331",
    pancard: "331",
    totalCompensation: "169.60",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "साक्षी",
    beneficiaryId: "mno901pqr567",
    khatauniSankhya: "16",
    serialNumber: "32",
    khasraNumber: "43/34",
    acquiredKhasraNumber: "43/34/35",
    areaVariety: "44",
    acquiredRakbha: "290",
    beneficiaryShare: "65",
    acquiredBeneficiaryShare: "00-01-54",
    landPricePerSqMt: "8100",
    villageName: "Two",
    verificationDetails: {
      level: "0",
      status: "",
      updatedBy: "",
      updatedAt: "",
      userRole: "",
      userName: "",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "सोलह",
    aadhar: "332",
    pancard: "332",
    totalCompensation: "172.70",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "0",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "विजय",
    beneficiaryId: "pqr012stu678",
    khatauniSankhya: "17",
    serialNumber: "33",
    khasraNumber: "44/35",
    acquiredKhasraNumber: "44/35/36",
    areaVariety: "45",
    acquiredRakbha: "295",
    beneficiaryShare: "66",
    acquiredBeneficiaryShare: "00-01-55",
    landPricePerSqMt: "8200",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सत्रह",
    aadhar: "333",
    pancard: "333",
    totalCompensation: "175.80",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "शेखर",
    beneficiaryId: "stu345vwx789",
    khatauniSankhya: "17",
    serialNumber: "34",
    khasraNumber: "45/36",
    acquiredKhasraNumber: "45/36/37",
    areaVariety: "46",
    acquiredRakbha: "300",
    beneficiaryShare: "67",
    acquiredBeneficiaryShare: "00-01-56",
    landPricePerSqMt: "8300",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सत्रह",
    aadhar: "334",
    pancard: "334",
    totalCompensation: "178.90",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अंजलि",
    beneficiaryId: "vwx456yzx890",
    khatauniSankhya: "18",
    serialNumber: "35",
    khasraNumber: "46/37",
    acquiredKhasraNumber: "46/37/38",
    areaVariety: "47",
    acquiredRakbha: "305",
    beneficiaryShare: "68",
    acquiredBeneficiaryShare: "00-01-57",
    landPricePerSqMt: "8400",
    villageName: "Four",
    villageId: "09yh4567898uyg",
    villageNameHindi: "अठारह",
    aadhar: "335",
    pancard: "335",
    totalCompensation: "182.00",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अर्पण",
    beneficiaryId: "yzx567abc901",
    khatauniSankhya: "18",
    serialNumber: "36",
    khasraNumber: "47/38",
    acquiredKhasraNumber: "47/38/39",
    areaVariety: "48",
    acquiredRakbha: "310",
    beneficiaryShare: "69",
    acquiredBeneficiaryShare: "00-01-58",
    landPricePerSqMt: "8500",
    villageName: "Four",
    villageId: "09yh4567898uyg",
    villageNameHindi: "अठारह",
    aadhar: "336",
    pancard: "336",
    totalCompensation: "185.10",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "संदीप",
    beneficiaryId: "abc678def012",
    khatauniSankhya: "19",
    serialNumber: "37",
    khasraNumber: "48/39",
    acquiredKhasraNumber: "48/39/40",
    areaVariety: "49",
    acquiredRakbha: "315",
    beneficiaryShare: "70",
    acquiredBeneficiaryShare: "00-01-59",
    landPricePerSqMt: "8600",
    villageName: "Five",
    villageId: "09yh4567898uyg",
    villageNameHindi: "उन्नीस",
    aadhar: "337",
    pancard: "337",
    totalCompensation: "188.20",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "प्रिय",
    beneficiaryId: "def789ghi345",
    khatauniSankhya: "19",
    serialNumber: "38",
    khasraNumber: "49/40",
    acquiredKhasraNumber: "49/40/41",
    areaVariety: "50",
    acquiredRakbha: "320",
    beneficiaryShare: "71",
    acquiredBeneficiaryShare: "00-01-60",
    landPricePerSqMt: "8700",
    villageName: "Five",
    villageId: "09yh4567898uyg",
    villageNameHindi: "उन्नीस",
    aadhar: "338",
    pancard: "338",
    totalCompensation: "191.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "अशोक",
    beneficiaryId: "ghi890jkl456",
    khatauniSankhya: "20",
    serialNumber: "39",
    khasraNumber: "50/41",
    acquiredKhasraNumber: "50/41/42",
    areaVariety: "51",
    acquiredRakbha: "325",
    beneficiaryShare: "72",
    acquiredBeneficiaryShare: "00-01-61",
    landPricePerSqMt: "8800",
    villageName: "Six",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बीस",
    aadhar: "339",
    pancard: "339",
    totalCompensation: "194.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "राहुल",
    beneficiaryId: "jkl901mno567",
    khatauniSankhya: "20",
    serialNumber: "40",
    khasraNumber: "51/42",
    acquiredKhasraNumber: "51/42/43",
    areaVariety: "52",
    acquiredRakbha: "330",
    beneficiaryShare: "73",
    acquiredBeneficiaryShare: "00-01-62",
    landPricePerSqMt: "8900",
    villageName: "Six",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बीस",
    aadhar: "340",
    pancard: "340",
    totalCompensation: "197.50",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "सुमन",
    beneficiaryId: "klm012nop345",
    khatauniSankhya: "21",
    serialNumber: "41",
    khasraNumber: "52/43",
    acquiredKhasraNumber: "52/43/44",
    areaVariety: "53",
    acquiredRakbha: "335",
    beneficiaryShare: "74",
    acquiredBeneficiaryShare: "00-01-63",
    landPricePerSqMt: "9000",
    villageName: "Seven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "इक्कीस",
    aadhar: "341",
    pancard: "341",
    totalCompensation: "200.60",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "रितेश",
    beneficiaryId: "nop123qrs456",
    khatauniSankhya: "21",
    serialNumber: "42",
    khasraNumber: "53/44",
    acquiredKhasraNumber: "53/44/45",
    areaVariety: "54",
    acquiredRakbha: "340",
    beneficiaryShare: "75",
    acquiredBeneficiaryShare: "00-01-64",
    landPricePerSqMt: "9100",
    villageName: "Seven",
    villageId: "09yh4567898uyg",
    villageNameHindi: "इक्कीस",
    aadhar: "342",
    pancard: "342",
    totalCompensation: "203.70",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "दीपक",
    beneficiaryId: "pqr234stu567",
    khatauniSankhya: "22",
    serialNumber: "43",
    khasraNumber: "54/45",
    acquiredKhasraNumber: "54/45/46",
    areaVariety: "55",
    acquiredRakbha: "345",
    beneficiaryShare: "76",
    acquiredBeneficiaryShare: "00-01-65",
    landPricePerSqMt: "9200",
    villageName: "Eight",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बाईस",
    aadhar: "343",
    pancard: "343",
    totalCompensation: "206.80",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "शिवानी",
    beneficiaryId: "stu345vwx678",
    khatauniSankhya: "22",
    serialNumber: "44",
    khasraNumber: "55/46",
    acquiredKhasraNumber: "55/46/47",
    areaVariety: "56",
    acquiredRakbha: "350",
    beneficiaryShare: "77",
    acquiredBeneficiaryShare: "00-01-66",
    landPricePerSqMt: "9300",
    villageName: "Eight",
    villageId: "09yh4567898uyg",
    villageNameHindi: "बाईस",
    aadhar: "344",
    pancard: "344",
    totalCompensation: "209.90",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "शिवेंद्र",
    beneficiaryId: "vwx456yzx789",
    khatauniSankhya: "23",
    serialNumber: "45",
    khasraNumber: "56/47",
    acquiredKhasraNumber: "56/47/48",
    areaVariety: "57",
    acquiredRakbha: "355",
    beneficiaryShare: "78",
    acquiredBeneficiaryShare: "00-01-67",
    landPricePerSqMt: "9400",
    villageName: "Nine",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तेईस",
    aadhar: "345",
    pancard: "345",
    totalCompensation: "213.00",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "दीप्ति",
    beneficiaryId: "xyz123abc456",
    khatauniSankhya: "23",
    serialNumber: "46",
    khasraNumber: "57/48",
    acquiredKhasraNumber: "57/48/49",
    areaVariety: "58",
    acquiredRakbha: "360",
    beneficiaryShare: "79",
    acquiredBeneficiaryShare: "00-01-68",
    landPricePerSqMt: "9500",
    villageName: "Nine",
    villageId: "09yh4567898uyg",
    villageNameHindi: "तेईस",
    aadhar: "346",
    pancard: "346",
    totalCompensation: "216.10",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "सुमित",
    beneficiaryId: "abc456def789",
    khatauniSankhya: "24",
    serialNumber: "47",
    khasraNumber: "58/49",
    acquiredKhasraNumber: "58/49/50",
    areaVariety: "59",
    acquiredRakbha: "365",
    beneficiaryShare: "80",
    acquiredBeneficiaryShare: "00-01-69",
    landPricePerSqMt: "9600",
    villageName: "Ten",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चौबीस",
    aadhar: "347",
    pancard: "347",
    totalCompensation: "219.20",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "अमृता",
    beneficiaryId: "def789ghi012",
    khatauniSankhya: "24",
    serialNumber: "48",
    khasraNumber: "59/50",
    acquiredKhasraNumber: "59/50/51",
    areaVariety: "60",
    acquiredRakbha: "370",
    beneficiaryShare: "81",
    acquiredBeneficiaryShare: "00-01-70",
    landPricePerSqMt: "9700",
    villageName: "Ten",
    villageId: "09yh4567898uyg",
    villageNameHindi: "चौबीस",
    aadhar: "348",
    pancard: "348",
    totalCompensation: "222.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "रिंकू",
    beneficiaryId: "ghi890jkl123",
    khatauniSankhya: "25",
    serialNumber: "49",
    khasraNumber: "60/51",
    acquiredKhasraNumber: "60/51/52",
    areaVariety: "61",
    acquiredRakbha: "375",
    beneficiaryShare: "82",
    acquiredBeneficiaryShare: "00-01-71",
    landPricePerSqMt: "9800",
    villageName: "Two",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "",
      updatedAt: "32 DEC 2011",
      userRole: "3",
      userName: "Karan",
      rejectionMessage: "Ase hi",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "पच्चीस",
    aadhar: "349",
    pancard: "349",
    totalCompensation: "225.40",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "नेहा",
    beneficiaryId: "jkl123mno456",
    khatauniSankhya: "25",
    serialNumber: "50",
    khasraNumber: "61/52",
    acquiredKhasraNumber: "61/52/53",
    areaVariety: "62",
    acquiredRakbha: "380",
    beneficiaryShare: "83",
    acquiredBeneficiaryShare: "00-01-72",
    landPricePerSqMt: "9900",
    villageName: "Two",
    verificationDetails: {
      level: "1",
      status: "1",
      updatedBy: "",
      updatedAt: "32 DEC 2011",
      userRole: "2",
      userName: "Nitish",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "पच्चीस",
    aadhar: "350",
    pancard: "350",
    totalCompensation: "228.50",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "1",
  },
  {
    beneficiaryName: "किरण",
    beneficiaryId: "mno456pqr789",
    khatauniSankhya: "26",
    serialNumber: "51",
    khasraNumber: "62/53",
    acquiredKhasraNumber: "62/53/54",
    areaVariety: "63",
    acquiredRakbha: "385",
    beneficiaryShare: "84",
    acquiredBeneficiaryShare: "00-01-73",
    landPricePerSqMt: "10000",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "छब्बीस",
    aadhar: "351",
    pancard: "351",
    totalCompensation: "231.60",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "रितेश",
    beneficiaryId: "pqr567stu890",
    khatauniSankhya: "26",
    serialNumber: "52",
    khasraNumber: "63/54",
    acquiredKhasraNumber: "63/54/55",
    areaVariety: "64",
    acquiredRakbha: "390",
    beneficiaryShare: "85",
    acquiredBeneficiaryShare: "00-01-74",
    landPricePerSqMt: "10100",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "छब्बीस",
    aadhar: "352",
    pancard: "352",
    totalCompensation: "234.70",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "सौरभ",
    beneficiaryId: "stu678vwx901",
    khatauniSankhya: "27",
    serialNumber: "53",
    khasraNumber: "64/55",
    acquiredKhasraNumber: "64/55/56",
    areaVariety: "65",
    acquiredRakbha: "395",
    beneficiaryShare: "86",
    acquiredBeneficiaryShare: "00-01-75",
    landPricePerSqMt: "10200",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सत्ताईस",
    aadhar: "353",
    pancard: "353",
    totalCompensation: "237.80",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "अंशु",
    beneficiaryId: "vwx789yzx012",
    khatauniSankhya: "27",
    serialNumber: "54",
    khasraNumber: "65/56",
    acquiredKhasraNumber: "65/56/57",
    areaVariety: "66",
    acquiredRakbha: "400",
    beneficiaryShare: "87",
    acquiredBeneficiaryShare: "00-01-76",
    landPricePerSqMt: "10300",
    villageName: "Three",
    villageId: "09yh4567898uyg",
    villageNameHindi: "सत्ताईस",
    aadhar: "354",
    pancard: "354",
    totalCompensation: "240.90",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationLevel: "0",
  },
  {
    beneficiaryName: "आशा",
    beneficiaryId: "yzx890abc123",
    khatauniSankhya: "28",
    serialNumber: "55",
    khasraNumber: "66/57",
    acquiredKhasraNumber: "66/57/58",
    areaVariety: "67",
    acquiredRakbha: "405",
    beneficiaryShare: "88",
    acquiredBeneficiaryShare: "00-01-77",
    landPricePerSqMt: "10400",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "1",
      updatedBy: "Nitin",
      updatedAt: "10 OCT 2024",
      userRole: "1",
      userName: "Nitin",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "0",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "अट्ठाईस",
    aadhar: "355",
    pancard: "355",
    totalCompensation: "244.00",
    paymentStatus: "2",
    paymentDate: "10/08/2024",
    verificationLevel: "0",
  },
  {
    beneficiaryName: "सोनू",
    beneficiaryId: "abc901def234",
    khatauniSankhya: "28",
    serialNumber: "56",
    khasraNumber: "67/58",
    acquiredKhasraNumber: "67/58/59",
    areaVariety: "68",
    acquiredRakbha: "410",
    beneficiaryShare: "89",
    acquiredBeneficiaryShare: "00-01-78",
    landPricePerSqMt: "10500",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "",
      updatedAt: "23 DEC 2024",
      userRole: "1",
      userName: "Rajesh",
      rejectionMessage: "Ase hi",
    },
    verificationDetails: {
      level: "1",
      status: "1",
      updatedBy: "Nitin",
      updatedAt: "10 OCT 2024",
      userRole: "1",
      userName: "Nitin",
      rejectionMessage: "",
    },
    isDocumentsUploaded: "1",
    documents: {
      landIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      strutureIndemnityBond:
        "https://barodaupbank.in/webdata/career/3-26-21/Guidelines%20for%20executing%20Indemnity%20Bond.pdf",
      affidavit:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      aadharCard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      pancard:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      checkORpassbook:
        "https://www.aicte-india.org/downloads/Anti_Ragging_affidavit.pdf",
      photo:
        "https://images.unsplash.com/photo-1624555130581-1d9cca783bc0?q=80&w=2071&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    },
    bankDetails: {
      email: "abc",
      accountNumber: "568568756",
      ifscCode: "AJJ09921",
      bankName: "ICICI Bank",
      bankBranch: "CHD",
      pancardNumber: "BSAPY0974T",
      aadharNumber: "82843934876",
      paymentInvoice:
        "https://slicedinvoices.com/pdf/wordpress-pdf-invoice-plugin-sample.pdf",
    },
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "अट्ठाईस",
    aadhar: "356",
    pancard: "356",
    totalCompensation: "247.10",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationLevel: "0",
  },
  {
    beneficiaryName: "नेहा",
    beneficiaryId: "def012ghi345",
    khatauniSankhya: "29",
    serialNumber: "57",
    khasraNumber: "68/59",
    acquiredKhasraNumber: "68/59/60",
    areaVariety: "69",
    acquiredRakbha: "415",
    beneficiaryShare: "90",
    acquiredBeneficiaryShare: "00-01-79",
    landPricePerSqMt: "10600",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "",
      updatedAt: "23 DEC 2024",
      userRole: "1",
      userName: "Rajesh",
      rejectionMessage: "Ase hi",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "उनत्तीस",
    aadhar: "357",
    pancard: "357",
    totalCompensation: "250.20",
    paymentStatus: "0",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "नीलम",
    beneficiaryId: "ghi123jkl456",
    khatauniSankhya: "29",
    serialNumber: "58",
    khasraNumber: "69/60",
    acquiredKhasraNumber: "69/60/61",
    areaVariety: "70",
    acquiredRakbha: "420",
    beneficiaryShare: "91",
    acquiredBeneficiaryShare: "00-01-80",
    landPricePerSqMt: "10700",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "",
      updatedAt: "23 DEC 2024",
      userRole: "1",
      userName: "Rajesh",
      rejectionMessage: "Ase hi",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "उनत्तीस",
    aadhar: "358",
    pancard: "358",
    totalCompensation: "253.30",
    paymentStatus: "1",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "0",
    hasQuery: "1",
    queryMessages: [
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "Hello",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "Yes",
        userRole: "1",
        name: "User 2",
      },
      {
        updatedBy: "user1",
        updatedAt: "12/10/2024",
        message: "How are you?",
        userRole: "2",
        name: "User 1",
      },
      {
        updatedBy: "user3",
        updatedAt: "12/10/2024",
        message: "Hey! How are you all",
        userRole: "3",
        name: "User 3",
      },
      {
        updatedBy: "user2",
        updatedAt: "12/10/2024",
        message: "I am good",
        userRole: "1",
        name: "User 2",
      },
    ],
  },
  {
    beneficiaryName: "माया",
    beneficiaryId: "jkl234mno567",
    khatauniSankhya: "30",
    serialNumber: "59",
    khasraNumber: "70/61",
    acquiredKhasraNumber: "70/61/62",
    areaVariety: "71",
    acquiredRakbha: "425",
    beneficiaryShare: "92",
    acquiredBeneficiaryShare: "00-01-81",
    landPricePerSqMt: "10800",
    villageName: "One",
    verificationDetails: {
      level: "1",
      status: "0",
      updatedBy: "",
      updatedAt: "23 DEC 2024",
      userRole: "1",
      userName: "Rajesh",
      rejectionMessage: "Ase hi",
    },
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "तीस",
    aadhar: "359",
    pancard: "359",
    totalCompensation: "256.40",
    paymentStatus: "2",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "2",
  },
  {
    beneficiaryName: "अविनाश",
    beneficiaryId: "klm345nop678",
    khatauniSankhya: "30",
    serialNumber: "60",
    khasraNumber: "71/62",
    acquiredKhasraNumber: "71/62/63",
    areaVariety: "72",
    acquiredRakbha: "430",
    beneficiaryShare: "93",
    acquiredBeneficiaryShare: "00-01-82",
    landPricePerSqMt: "10900",
    villageName: "One",
    isDocumentsUploaded: "0",
    villageId: "09yh4567898uyg",
    isDisbursememtUploaded: "1",
    disbursementDetails: {
      bhumiPrice: 2500000,
      faldaarBhumiPrice: 50000,
      gairFaldaarBhumiPrice: 0,
      housePrice: 1200000,
      toshan: 3750000,
      interest: 45000,
      totalCompensation: 7545000,
      vivran: "This is good",
    },
    villageNameHindi: "तीस",
    aadhar: "360",
    pancard: "360",
    totalCompensation: "259.50",
    paymentStatus: "2",
    paymentDate: "10/08/2024",
    verificationStatus: "1",
    verificationLevel: "2",
  },
];
